{
 "title": "Data Layer",
 "description": "metrics for the data layer",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(atomix_role,cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(atomix_role{cluster=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "physicalTenant",
    "query": {
     "query": "label_values(zeebe_health{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"},physicalTenant)"
    }
   },
   {
    "name": "partition",
    "query": {
     "query": "label_values(atomix_role{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", pod=~\"$pod\"},partition)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "pod",
    "query": {
     "query": "label_values(atomix_role{cluster=~\"$cluster\", namespace=~\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Operate Importer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput Exported and Imported records (avg)",
     "type": "timeseries",
     "description": "Throughput of documents processed and imported.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 887 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(operate_events_processed_total{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[$__rate_interval])) by (status)",
       "legendFormat": "imported"
      },
      {
       "expr": "sum(rate(zeebe_exporter_events_total{namespace=~\"$namespace\", action=~\"exported\",physicalTenant=~\"$physicalTenant\", partition=~\"$partition\", valueType!~\"MESSAGE_SUBSCRIPTION|MESSAGE|JOB_BATCH\"}[$__rate_interval]))",
       "legendFormat": "exported"
      }
     ]
    },
    {
     "title": "Latency (avg)",
     "type": "timeseries",
     "description": "Shows the time (latency) between writing the command to the dispatcher, processing, exporting, and then importing the record.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 894 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(operate_import_time_seconds_sum{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}[$__rate_interval])) / sum(rate(operate_import_time_seconds_count{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Import latency"
      },
      {
       "expr": "sum(rate(zeebe_stream_processor_latency_sum{namespace=~\"$namespace\",physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"}[$__rate_interval]) or rate(zeebe_stream_processor_latency_seconds_sum{namespace=~\"$namespace\",physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"}[$__rate_interval])) / sum(rate(zeebe_stream_processor_latency_count{namespace=~\"$namespace\",physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"}[$__rate_interval]) or rate(zeebe_stream_processor_latency_seconds_count{namespace=~\"$namespace\",physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"}[$__rate_interval]))",
       "legendFormat": "Processing latency"
      },
      {
       "expr": "sum(rate(zeebe_exporting_latency_sum{namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"}[$__rate_interval])) / sum(rate(zeebe_exporting_latency_count{namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"}[$__rate_interval]))",
       "legendFormat": "Exporting latency"
      }
     ]
    },
    {
     "title": "Importing: read duration",
     "type": "timeseries",
     "description": "The time it takes for the importer to read an record on average from ES",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 899 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(operate_import_query_seconds_sum{namespace=\"$namespace\"}[$__rate_interval])) by (type) / sum(rate(operate_import_query_seconds_count{namespace=\"$namespace\"}[$__rate_interval])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Import processing duration (AVG)",
     "type": "timeseries",
     "description": "Time the import writer thread needs on average to process an ImportBatch (containing several Zeebe records).",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 899 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(operate_import_processing_duration_seconds_sum{namespace=\"$namespace\"}[$__rate_interval])) by (type) / sum(rate(operate_import_processing_duration_seconds_count{namespace=\"$namespace\"}[$__rate_interval])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Importing: write duration (avg)",
     "type": "timeseries",
     "description": "The time it takes to write the bulk requests (during importing) to ES on average.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 899 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(operate_import_index_query_seconds_sum{namespace=\"$namespace\"}[$__rate_interval])) by (type) / sum(rate(operate_import_index_query_seconds_count{namespace=\"$namespace\"}[$__rate_interval])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Import queue size",
     "type": "timeseries",
     "description": "There is a queue of import jobs where each job has to import a batch of records. This details how many such jobs are currently in the queue.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 907 },
     "targets": [
      {
       "expr": "sum(operate_import_queue_size{namespace=~\"$namespace\", pod=~\"$pod\"} ) by (type)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Operate Archiver",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true
  },
  {
   "title": "Camunda Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Camunda Exporter (Flush Duration)",
     "type": "heatmap",
     "description": "Each time a non empty bulk request if flushed, this is how long the flush takes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_camunda_exporter_flush_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Camunda Exporter (Flush Failure Rate)",
     "type": "gauge",
     "description": "The rate of failure of flush operations, averaged over 15s intervals",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(zeebe_camunda_exporter_failed_flush_total{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", pod=~\"$pod\"}[$__rate_interval]) / rate(zeebe_camunda_exporter_flush_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}} Exporter {{partition}}"
      }
     ]
    },
    {
     "title": "Camunda Exporter (Flush Failure Type)",
     "type": "timeseries",
     "description": "When bulk request flushes fail, the type of error returned is counted.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 147 },
     "targets": [
      {
       "expr": "increase(zeebe_camunda_exporter_flush_failure_type_total{cluster=~\"$cluster\", namespace=~\"$namespace\",physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Camunda Exporter (Time since last flush)",
     "type": "timeseries",
     "description": "The time in seconds since the last flush.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 147 },
     "targets": [
      {
       "expr": "min by (physicalTenant, partition) (zeebe_camunda_exporter_since_last_flush_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"})",
       "legendFormat": "{{physicalTenant}} partition-{{partition}}"
      }
     ]
    },
    {
     "title": "Camunda Exporter (Records to export backlog)",
     "type": "timeseries",
     "description": "How far behind each exporter is from exporting the records which have been committed.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 155 },
     "targets": [
      {
       "expr": "max (zeebe_log_appender_last_committed_position{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"}) by (physicalTenant, partition) - max (zeebe_exporter_last_exported_position{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", partition=~\"$partition\", exporter=~\"(?i)camundaexporter\"}) by (physicalTenant, partition)",
       "legendFormat": "{{physicalTenant}} partition {{partition}}"
      }
     ]
    },
    {
     "title": "Camunda Exporter (Bulk Size)",
     "type": "timeseries",
     "description": "For every non empty flush of a bulk request, this is the number of entities flushed.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 155 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_camunda_exporter_bulk_size_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"}[$__rate_interval])) by (physicalTenant, partition) / \nsum(increase(zeebe_camunda_exporter_bulk_size_count{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"}[$__rate_interval])) by (physicalTenant, partition)",
       "legendFormat": "{{physicalTenant}} partition-{{partition}}"
      }
     ]
    },
    {
     "title": "Camunda Exporter (Flush Latency)",
     "type": "timeseries",
     "description": "How long an export request is open and collecting new records before flushing.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "targets": [
      {
       "expr": "min by (physicalTenant, partition) (\n  rate(zeebe_camunda_exporter_flush_latency_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", partition=~\"$partition\", pod=~\"$pod\"}[$__rate_interval]) / \n  rate(zeebe_camunda_exporter_flush_latency_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\",physicalTenant=~\"$physicalTenant\", partition=~\"$partition\", pod=~\"$pod\"}[$__rate_interval])\n)",
       "legendFormat": "{{physicalTenant}} Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Process cache eviction",
     "type": "timeseries",
     "description": "Shows the rate of evictions of the process cache",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 163 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_camunda_exporter_cache_process_evictions_total{namespace=~\"$namespace\",physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"}[$__rate_interval])) by (physicalTenant, partition)",
       "legendFormat": "{{physicalTenant}} Evictions {{partition}}"
      }
     ]
    },
    {
     "title": "Process cache access",
     "type": "timeseries",
     "description": "Shows the rate of access to the process cache per partition",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 171 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_camunda_exporter_cache_process_result_total{namespace=~\"$namespace\",physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"}[$__rate_interval])) by (physicalTenant, partition)",
       "legendFormat": "{{physicalTenant}} Cache access {{partition}}"
      },
      {
       "expr": "sum(rate(zeebe_camunda_exporter_cache_process_result_total{namespace=~\"$namespace\",physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"}[$__rate_interval])) by (physicalTenant, partition, type)",
       "legendFormat": "{{physicalTenant}} P{{partition}} - {{type}}"
      }
     ]
    },
    {
     "title": "Cache load duration",
     "type": "heatmap",
     "description": "The time the cache spent computing or retrieving the new value",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 171 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_camunda_exporter_cache_process_load_duration_failure_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(increase(zeebe_camunda_exporter_cache_process_load_duration_failure_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Archiving - Search request duration",
     "type": "heatmap",
     "description": "Historgram, to show the distribution of the duration of search requests to find completed entities, which should be archived.",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 179 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_camunda_exporter_archiver_request_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", partition=~\"$partition\", type=\"search\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Archiving - Reindex request duration",
     "type": "heatmap",
     "description": "Historgram, to show the distribution of durations reindex requests take, to copy data from runtime to dated indices.",
     "gridPos": { "h": 8, "w": 8, "x": 7, "y": 179 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_camunda_exporter_archiver_request_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", partition=~\"$partition\", type=\"reindex\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Archiving - Delete request duration",
     "type": "heatmap",
     "description": "Historgram, to show the distribution of durations delete requests take, to delete data from runtime indices.",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 179 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_camunda_exporter_archiver_request_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", partition=~\"$partition\", type=\"delete\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Cache load rate",
     "type": "timeseries",
     "description": "The rate of the loading data into the cache",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 187 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_camunda_exporter_cache_process_load_duration_success_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"}[$__rate_interval])) by (physicalTenant, partition)",
       "legendFormat": "{{physicalTenant}} Success p{{partition}}"
      },
      {
       "expr": "sum(rate(zeebe_camunda_exporter_cache_process_load_duration_failure_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"}[$__rate_interval])) by (physicalTenant, partition)",
       "legendFormat": "{{physicalTenant}} Failure p{{partition}}"
      }
     ]
    },
    {
     "title": "Camunda Exporter (Process Instances Awaiting Archival)",
     "type": "timeseries",
     "description": "Process instances which can be archived but are waiting to do so.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 187 },
     "targets": [
      {
       "expr": "max by (physicalTenant, partition) (zeebe_camunda_exporter_process_instances_awaiting_archival{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"})",
       "legendFormat": "{{physicalTenant}} Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Archiving duration",
     "type": "heatmap",
     "description": "Histogram to show the distribution of the overall archiving duration, which includes searching, reindexing, and deletion.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 195 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_camunda_exporter_archiver_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Archiving",
     "type": "timeseries",
     "description": "Shows the rate of archiving (in-progress) and archived process instance and batch operations. Batch operations or process instances need to be completed before being able to be archived. The rate is aggregated by partition.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 195 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_camunda_exporter_archiver_process_instances_total{namespace=~\"$namespace\",physicalTenant=~\"$physicalTenant\", partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (physicalTenant, partition, state)",
       "legendFormat": "{{physicalTenant}} {{state}} process instances [p{{partition}}]"
      },
      {
       "expr": "sum(rate(zeebe_camunda_exporter_archiver_batch_operations_total{namespace=~\"$namespace\",physicalTenant=~\"$physicalTenant\", partition=~\"$partition\",pod=~\"$pod\"}[$__rate_interval])) by (physicalTenant, partition, state)",
       "legendFormat": "{{physicalTenant}} {{state}} batch operations [p{{partition}}]"
      }
     ]
    },
    {
     "title": "Camunda Exporter (Pending incident updates)",
     "type": "timeseries",
     "description": "Incidents that have not yet been processed by the update task.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 203 },
     "targets": [
      {
       "expr": "max by (physicalTenant, partition) (zeebe_camunda_exporter_incident_updates_pending{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"})",
       "legendFormat": "{{physicalTenant}} Partition {{partition}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ElasticSearch Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Elasticsearch Exporter (Flush Duration)",
     "type": "heatmap",
     "description": "Each time a non empty bulk request if flushed, this is how long the flush takes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 636 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_elasticsearch_exporter_flush_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Elasticsearch Exporter (Flush Failure Rate)",
     "type": "timeseries",
     "description": "The rate of failure of flush operations, averaged over 15s intervals",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 636 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(zeebe_elasticsearch_exporter_failed_flush_total{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", pod=~\"$pod\"}[$__rate_interval]) / rate(zeebe_elasticsearch_exporter_flush_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}} Exporter {{partition}}"
      }
     ]
    },
    {
     "title": "Elasticsearch Exporter (Bulk Size)",
     "type": "heatmap",
     "description": "For every non empty flush of a bulk request, this is the number of entities flushed.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 662 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_elasticsearch_exporter_bulk_size_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Elasticsearch Exporter (Bulk Memory Size)",
     "type": "timeseries",
     "description": "Each bulk request has a number of records, the memory usage to flush this bulk request is crudely measured through content length and tracked here. ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 662 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "zeebe_elasticsearch_exporter_bulk_memory_size{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"}",
       "legendFormat": "{{physicalTenant}} {{pod}} p{{partition}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RDBMS Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "RDBMS Exporter (Flush Duration)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_rdbms_exporter_flush_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "RDBMS Exporter (Flush Latency)",
     "type": "heatmap",
     "description": "How long an export request is open and collecting new records before flushing.",
     "gridPos": { "h": 8, "w": 11, "x": 10, "y": 7 },
     "targets": [
      {
       "expr": "rate(zeebe_rdbms_exporter_flush_latency_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", pod=~\"$pod\"}[$__rate_interval]) / rate(zeebe_rdbms_exporter_flush_latency_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", pod=~\"$pod\"}[$__rate_interval]) > 0",
       "legendFormat": "{{pod}} Exporter {{partition}}"
      }
     ]
    },
    {
     "title": "RDBMS Exporter (Flush Failure Rate)",
     "type": "gauge",
     "description": "The rate of failure of flush operations, averaged over 15s intervals",
     "gridPos": { "h": 8, "w": 3, "x": 21, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(zeebe_rdbms_exporter_failed_flush_total{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", pod=~\"$pod\"}[$__rate_interval]) / rate(zeebe_rdbms_exporter_flush_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}} Exporter {{partition}}"
      }
     ]
    },
    {
     "title": "RDBMS Exporter (Bulk Size)",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_rdbms_exporter_bulk_size_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "RDBMS Exporter JDBC Statements Batch factor",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 11, "y": 15 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_rdbms_exporter_enqueued_statements_total{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"}[$__rate_interval])) / sum(increase(zeebe_rdbms_exporter_executed_statements_total{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"}[$__rate_interval]))",
       "legendFormat": "SQL Batch factor"
      },
      {
       "expr": "sum(increase(zeebe_rdbms_exporter_merged_queue_item_total{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"}[$__rate_interval])) / sum(increase(zeebe_rdbms_exporter_enqueued_statements_total{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"}[$__rate_interval]))",
       "legendFormat": "QueueItem merge factor"
      }
     ]
    },
    {
     "title": "RDBMS Exporter Statements",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 5, "x": 19, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(zeebe_rdbms_exporter_executed_statements_total{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", partition=~\"$partition\"}[$__rate_interval])) by (statementId)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "RDBMS Execution Queue Memory Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(zeebe_rdbms_exporter_queue_memory_bytes_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", pod=~\"$pod\"}[$__rate_interval]) / rate(zeebe_rdbms_exporter_queue_memory_bytes_count{cluster=~\"$cluster\", namespace=~\"$namespace\", physicalTenant=~\"$physicalTenant\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HikariCP Connections (Active/Idle, by node)",
     "type": "timeseries",
     "description": "HikariCP client-pool connections opened by each Camunda pod towards Postgres (or PgBouncer, if enabled), per physical tenant.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(hikaricp_connections_active{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", physicalTenant=~\"$physicalTenant\"}) by (pod, physicalTenant)",
       "legendFormat": "{{pod}} {{physicalTenant}} active"
      },
      {
       "expr": "sum(hikaricp_connections_idle{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", physicalTenant=~\"$physicalTenant\"}) by (pod, physicalTenant)",
       "legendFormat": "{{pod}} {{physicalTenant}} idle"
      }
     ]
    },
    {
     "title": "HikariCP Pool Utilization",
     "type": "timeseries",
     "description": "HikariCP pool utilization per Camunda pod (active connections ÷ configured maximum pool size).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(hikaricp_connections_active{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", physicalTenant=~\"$physicalTenant\"}) by (pod, physicalTenant)\n/\nsum(hikaricp_connections_max{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", physicalTenant=~\"$physicalTenant\"}) by (pod, physicalTenant)",
       "legendFormat": "{{pod}} {{physicalTenant}}"
      }
     ]
    },
    {
     "title": "PgBouncer Client Pool (Active/Waiting)",
     "type": "timeseries",
     "description": "PgBouncer client-side pool (Camunda pods → PgBouncer), by Postgres database/user. cl_active = linked to a server; cl_waiting = queued for one (backpressure signal). Only populated when the CNPG Pooler is enabled. No per-pod breakdown is available here: PgBouncer's transaction pooling severs the 1:1 client-to-server mapping, so node attribution lives on the HikariCP panel above instead.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(cnpg_pgbouncer_pools_cl_active{cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (database, user)",
       "legendFormat": "{{database}} ({{user}}) active"
      },
      {
       "expr": "sum(cnpg_pgbouncer_pools_cl_waiting{cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (database, user)",
       "legendFormat": "{{database}} ({{user}}) waiting"
      }
     ]
    },
    {
     "title": "PgBouncer Server Pool (Active/Idle/Used)",
     "type": "timeseries",
     "description": "PgBouncer server-side pool (PgBouncer → Postgres), by database/user — the real number of backend connections the pool is holding open. sv_used connections were used but are not yet reset/returned to the pool.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(cnpg_pgbouncer_pools_sv_active{cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (database, user)",
       "legendFormat": "{{database}} ({{user}}) active"
      },
      {
       "expr": "sum(cnpg_pgbouncer_pools_sv_idle{cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (database, user)",
       "legendFormat": "{{database}} ({{user}}) idle"
      },
      {
       "expr": "sum(cnpg_pgbouncer_pools_sv_used{cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (database, user)",
       "legendFormat": "{{database}} ({{user}}) used"
      }
     ]
    },
    {
     "title": "Postgres Backend Connections (by state)",
     "type": "timeseries",
     "description": "Real PostgreSQL backend connections, by state, from the CNPG Cluster's own metrics — the authoritative count regardless of whether PgBouncer is in front of it.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(cnpg_backends_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (state)",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Postgres Connections Utilization",
     "type": "timeseries",
     "description": "Total Postgres backend connections ÷ max_connections. Useful whether or not PgBouncer is in front of the cluster.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(cnpg_backends_total{cluster=~\"$cluster\", namespace=~\"$namespace\"})\n/\nsum(cnpg_pg_settings_setting{cluster=~\"$cluster\", namespace=~\"$namespace\", name=\"max_connections\"})",
       "legendFormat": "utilization"
      }
     ]
    }
   ]
  },
  {
   "title": "Schema Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Physical Tenant Readiness (Ready vs Total)",
     "type": "timeseries",
     "description": "Count of physical tenants whose secondary storage is ready (ready on every currently-scraped node) versus the total known physical tenants. A gap between the two lines, or Total dropping, needs investigation via the per-tenant panel below.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(min by (physicalTenant) (camunda_physical_tenant_secondary_storage_ready{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", physicalTenant=~\"$physicalTenant\"}) == 1)",
       "legendFormat": "Ready PTs"
      },
      {
       "expr": "count(count by (physicalTenant) (camunda_physical_tenant_secondary_storage_ready{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", physicalTenant=~\"$physicalTenant\"}))",
       "legendFormat": "Total PTs"
      }
     ]
    },
    {
     "title": "Physical Tenant Readiness (per tenant)",
     "type": "stat",
     "description": "Per-physical-tenant secondary storage readiness: worst case (min) across currently-scraped nodes. A tenant not scraped within Prometheus' staleness window (5m) drops out of this panel entirely rather than showing red; check the panel above and node liveness in that case.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min by (physicalTenant) (camunda_physical_tenant_secondary_storage_ready{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", physicalTenant=~\"$physicalTenant\"})",
       "legendFormat": "{{physicalTenant}}"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "timeseries",
     "description": "Time taken to init secondary storage schema.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "repeat": "namespace",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (pod) (camunda_schema_init_time_seconds_max{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "{{pod}} schema init"
      }
     ]
    }
   ]
  }
 ]
}